---
- hosts: all

  vars_prompt:
  - name: 'magento_version'
    prompt: 'Which Magento version will be installed: 1 - 1.x,  2 - 2.x ?'
    default: '2'

  - name: 'php_version'
    prompt: 'Which PHP version should be installed: 5.5, 5.6, 7.0 ?'
    default: '7.0'

  - name: 'web_server'
    prompt: 'Which web server would you like to use: NginX, Apache ?'
    default: 'nginx'

  - name: 'update_all_packages'
    prompt: 'Update all packages ?'
    default: 'yes'

  tasks:
  - debug: msg="Magento {{ magento_version }} | PHP {{ php_version }} | Web server {{ web_server }}"

  - name: Upgrade all packages
    yum: name=* state=latest
    when: update_all_packages == 'yes'

  - name: Remove sendmail
    yum: name=sendmail state=absent

  - name: Import Remi GPG Key
    rpm_key: key=http://rpms.famillecollet.com/RPM-GPG-KEY-remi state=present

  - name: Install repos
    yum: name={{ item }} state=present
    with_items:
      - epel-release
      - http://www.city-fan.org/ftp/contrib/yum-repo/rhel6/x86_64/city-fan.org-release-1-13.rhel6.noarch.rpm
      - http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

  - name: Install utility packages and services
    yum: name={{ item }} state=latest
    with_items:
      - yum-utils
      - bind-utils
      - curl
      - cronie
      - git
      - patch
      - redis

  - name: Configure bashrc
    copy: src=files/config/bash/bashrc dest=/etc/bashrc

  - name: Enable repo for PHP 5.5
    command: yum-config-manager --enable remi-php55
    when: php_version == '5.5' and magento_version == '1'

  - name: Enable repo for PHP 5.6
    command: yum-config-manager --enable remi-php56
    when: php_version == '5.6' and magento_version == '2'

  - name: Enable repo for PHP 7.0
    command: yum-config-manager --enable remi-php70
    when: php_version == '7.0' and magento_version == '2'

  - name: Install NginX, Apache, Supervisor
    yum: name={{ item }} state=latest
    with_items:
      - nginx
      - httpd
      - supervisor

  - name: Check if PHP was installed with expected version
    command: rpm -q php-{{ php_version }}*
    register: php_version_check
    failed_when: php_version_check.rc > 1
    changed_when: no

  - name: Remove current PHP with extensions
    yum: name=php* state=absent
    when: php_version_check.rc == 1

  - name: Install PHP with extensions
    yum: name={{ item }} state=present
    with_items:
      - php
      - php-bcmath
      - php-cli
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-pdo
      - php-pecl-igbinary
      - php-pecl-imagick
      - php-pecl-oauth
      - php-pecl-redis
      - php-pecl-zendopcache
      - php-process
      - php-soap
      - php-xml
      - php-zip

  - name: Disable all remi-php* repoes
    command: yum-config-manager --disable remi-php{{ item }}
    with_items:
      - 55
      - 56
      - 70

  - name: Install composer
    get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=755

  - name: Enable shell for apache user    
    user: name=apache shell=/bin/bash home=/var/www

  - name: Change owner of /var/www to apache
    file: path=/var/www owner=apache group=apache recurse=yes state=directory

  - name: Dedaemon NginX
    lineinfile: dest=/etc/nginx/nginx.conf insertbefore=BOF line="daemon off;" state=present

  - name: Put NginX under apache user
    lineinfile: dest=/etc/nginx/nginx.conf regexp="^user" line="user apache;" state=present

  - name: Prepare NginX configuration
    template: src=files/config/nginx/magento.conf.j2 dest=/etc/nginx/conf.d/default.conf force=yes

  - name: Prepare Apache configuration
    template: src=files/config/httpd/httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf force=yes

  - name: Prepare Supervisor configuration
    template: src=files/config/supervisor/supervisord.conf.j2 dest=/etc/supervisord.conf force=yes

  - name: Configure PHP-FPM
    copy: src=files/config/php/www.conf dest=/etc/php-fpm.d/www.conf force=yes
    notify:
      - Supervisor Apply

  - name: Disable services auto-start
    service: name={{ item }} state=stopped enabled=no
    with_items:
      - nginx
      - httpd

  - name: Enable services auto-start
    service: name={{ item }} state=restarted enabled=yes
    with_items:
      - crond
      - sshd
      - supervisord
      - redis

  handlers:
  - name: Supervisor Apply
    service: name=supervisord state=restarted
