---
- hosts: all

  vars_prompt:
  - name: 'magento_version'
    prompt: 'Which Magento version will be installed: 1 - 1.x,  2 - 2.x ?'
    default: '2'

  - name: 'php_version'
    prompt: 'Which PHP version should be installed: 5.5, 5.6, 7.0 ?'
    default: '7.0'

  - name: 'web_server'
    prompt: 'Which web server would you like to use: NginX, Apache ?'
    default: 'nginx'

  - name: 'update_all_packages'
    prompt: 'Update all packages ?'
    default: 'yes'


  tasks:
  # Print out user's inputs
  - debug: msg="Magento {{ magento_version }} | PHP {{ php_version }} | Web server {{ web_server }}"

  # Preparation
  - name: Upgrade all packages
    yum: name=* state=latest
    when: update_all_packages == 'yes'
    tags:
      - preparation

  - name: Remove sendmail
    yum: name=sendmail state=absent
    tags:
      - preparation

  - name: Import Remi GPG Key
    rpm_key: key=http://rpms.famillecollet.com/RPM-GPG-KEY-remi state=present
    tags:
      - preparation

  - name: Install repos centos 6
    yum: name={{ item }} state=present
    with_items:
      - epel-release
      - http://www.city-fan.org/ftp/contrib/yum-repo/rhel6/x86_64/city-fan.org-release-1-13.rhel6.noarch.rpm
      - http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
    tags:
      - preparation

  - name: Install repos centos 7
    yum: name={{ item }} state=present
    with_items:
      - epel-release
      - http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
      - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
    tags:
      - preparation


  # Install common packages
  - name: Install utility packages and services
    yum: name={{ item }} state=latest
    with_items:
      - yum-utils
      - bind-utils
      - curl
      - cronie
      - git
      - patch
      - redis
    tags:
      - install-common-packages

  - name: Configure bashrc
    copy: src=files/config/bash/bashrc dest=/etc/bashrc

  
  # Setup PHP repos
  - name: Enable repo for PHP 5.5
    command: yum-config-manager --enable remi-php55
    when: php_version == '5.5' and magento_version == '1'
    tags:
      - setup-php-repo

  - name: Enable repo for PHP 5.6
    command: yum-config-manager --enable remi-php56
    when: php_version == '5.6' and magento_version == '2'
    tags:
      - setup-php-repo

  - name: Enable repo for PHP 7.0
    command: yum-config-manager --enable remi-php70
    when: php_version == '7.0' and magento_version == '2'
    tags:
      - setup-php-repo


  # Setup web server, will run under supervisord
  - name: Install NginX, Apache, Supervisor
    yum: name={{ item }} state=latest
    with_items:
      - nginx
      - httpd
      - supervisor
    tags:
      - setup-web-server

  - name: Check supervisor version 3 or not (then should be 2)
    command: rpm -q supervisor-3.*
    register: supervisor_version_check
    failed_when: supervisor_version_check.rc > 1
    changed_when: no
    tags:
      - setup-web-server

  - name: Check apache version 2.4 or not (then should be 2.2)
    command: rpm -q httpd-2.4.*
    register: httpd_version_check
    failed_when: httpd_version_check.rc > 1
    changed_when: no
    tags:
      - setup-web-server

  - name: Check if PHP was installed with expected version
    command: rpm -q php-{{ php_version }}*
    register: php_version_check
    failed_when: php_version_check.rc > 1
    changed_when: no
    tags:
      - setup-web-server

  - name: Remove current PHP with extensions
    yum: name=php* state=absent
    when: php_version_check.rc == 1
    tags:
      - setup-web-server

  - name: Install PHP with extensions
    yum: name={{ item }} state=present
    with_items:
      - php
      - php-bcmath
      - php-cli
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-pdo
      - php-pecl-igbinary
      - php-pecl-imagick
      - php-pecl-oauth
      - php-pecl-redis
      - php-pecl-zendopcache
      - php-process
      - php-soap
      - php-xml
      - php-zip
    tags:
      - setup-web-server

  - name: Disable all remi-php* repoes
    command: yum-config-manager --disable remi-php{{ item }}
    with_items:
      - 55
      - 56
      - 70
    tags:
      - setup-web-server

  # Install tools for Dev Env
  - name: Install composer
    get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=755
    when: magento_version == '2'
    tags:
      - setup-web-server

  - name: Install nodejs repo
    shell: curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
    when: magento_version == '2'
    tags:
      - setup-web-server

  - name: Install Nodejs
    yum: name=nodejs state=present
    when: magento_version == '2'
    tags:
      - setup-web-server

  - name: Install grunt-cli
    npm: name=grunt-cli global=yes
    when: magento_version == '2'
    tags:
      - setup-web-server
      
  - name: Enable shell for apache user    
    user: name=apache shell=/bin/bash home=/var/www
    tags:
      - setup-web-server

  - name: Change owner of /var/www to apache
    file: path=/var/www owner=apache group=apache recurse=yes state=directory
    tags:
      - setup-web-server

  - name: Dedaemon NginX
    lineinfile: dest=/etc/nginx/nginx.conf insertbefore=BOF line="daemon off;" state=present
    tags:
      - setup-web-server

  - name: Put NginX under apache user
    lineinfile: dest=/etc/nginx/nginx.conf regexp="^user" line="user apache;" state=present
    tags:
      - setup-web-server

  - name: Prepare NginX configuration
    template: src=files/config/nginx/magento.conf.j2 dest=/etc/nginx/conf.d/default.conf
    tags:
      - setup-web-server

  - name: Prepare Apache 2.2 configuration
    template: src=files/config/httpd/httpd-2.2.conf.j2 dest=/etc/httpd/conf/httpd.conf
    when: httpd_version_check.rc == 1
    tags:
      - setup-web-server

  - name: Prepare Apache 2.4 configuration
    template: src=files/config/httpd/httpd-2.4.conf.j2 dest=/etc/httpd/conf/httpd.conf
    when: httpd_version_check.rc == 0
    tags:
      - setup-web-server

  - name: Prepare Supervisor 2 configuration
    template: src=files/config/supervisor/supervisord-2.conf.j2 dest=/etc/supervisord.conf
    when: supervisor_version_check.rc == 1
    tags:
      - setup-web-server

  - name: Prepare Supervisor 3 configuration
    template: src=files/config/supervisor/supervisord-3.conf.j2 dest=/etc/supervisord.conf
    when: supervisor_version_check.rc == 0
    tags:
      - setup-web-server

  - name: Configure PHP-FPM
    copy: src=files/config/php/www.conf dest=/etc/php-fpm.d/www.conf
    notify:
      - Supervisor Apply
    tags:
      - setup-web-server


  # Ensure services are enabled or not      
  - name: Disable services auto-start
    service: name={{ item }} state=stopped enabled=no
    with_items:
      - nginx
      - httpd
    tags:
      - service-status

  - name: Enable services auto-start
    service: name={{ item }} state=restarted enabled=yes
    with_items:
      - crond
      - sshd
      - supervisord
      - redis
    tags:
      - service-status


  handlers:
  - name: Supervisor Apply
    service: name=supervisord state=restarted
